//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountdownWordFinder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CountdownWordFinder.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;aadeh&quot;:[&quot;aahed&quot;,&quot;ahead&quot;],&quot;aaghin&quot;:[&quot;aahing&quot;],&quot;aaiil&quot;:[&quot;aalii&quot;],&quot;aaiils&quot;:[&quot;aaliis&quot;,&quot;sialia&quot;],&quot;aaadkrrv&quot;:[&quot;aardvark&quot;],&quot;aaadkrrsv&quot;:[&quot;aardvarks&quot;],&quot;aadflorw&quot;:[&quot;aardwolf&quot;],&quot;aaghr&quot;:[&quot;aargh&quot;,&quot;agrah&quot;,&quot;hagar&quot;],&quot;aanor&quot;:[&quot;aaron&quot;],&quot;aacinor&quot;:[&quot;aaronic&quot;,&quot;nicarao&quot;,&quot;ocarina&quot;],&quot;aaacilnor&quot;:[&quot;aaronical&quot;],&quot;aaeinort&quot;:[&quot;aaronite&quot;,&quot;aeration&quot;],&quot;aaciinort&quot;:[&quot;aaronitic&quot;],&quot;aaghrr&quot;:[&quot;aarrgh&quot;],&quot;aaghhrr&quot;:[&quot;aarrghh&quot;],&quot;aaeglosv&quot;:[&quot;aasvogel&quot;],&quot;aaeglossv&quot;:[&quot;aasvogels&quot;],&quot;aabbdeh&quot;:[&quot;ababdeh&quot;],&quot;aaabbu&quot;:[&quot;ababua&quot;],&quot;aaabc&quot;:[&quot;abaca&quot;,&quot;caaba&quot;,&quot;cab [rest of string was tru....
        /// </summary>
        internal static string dictionary {
            get {
                return ResourceManager.GetString("dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///aa
        ///aaa
        ///aah
        ///aahed
        ///aahing
        ///aahs
        ///aal
        ///aalii
        ///aaliis
        ///aals
        ///aam
        ///aani
        ///aardvark
        ///aardvarks
        ///aardwolf
        ///aardwolves
        ///aargh
        ///aaron
        ///aaronic
        ///aaronical
        ///aaronite
        ///aaronitic
        ///aarrgh
        ///aarrghh
        ///aaru
        ///aas
        ///aasvogel
        ///aasvogels
        ///ab
        ///aba
        ///ababdeh
        ///ababua
        ///abac
        ///abaca
        ///abacay
        ///abacas
        ///abacate
        ///abacaxi
        ///abaci
        ///abacinate
        ///abacination
        ///abacisci
        ///abaciscus
        ///abacist
        ///aback
        ///abacli
        ///abacot
        ///abacterial
        ///abactinal
        ///abactinally
        ///abaction
        ///abactor
        ///abaculi
        ///abaculus
        ///abacus
        ///abacuses
        ///abada
        ///abaddon
        ///abadejo
        ///abadengo
        ///abadia [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dictionaryText {
            get {
                return ResourceManager.GetString("dictionaryText", resourceCulture);
            }
        }
    }
}
